# -*- coding: utf-8 -*-
# @Time    : 2022/05/23 19:14
# @Author  : liyang
# @FileName: 数据库配置文件        120  mde  extranet
# @Software: PyCharm

-
  environment: "extranet"

-
# 测试环境mysql配置
  mysql_config:
    host: '192.168.10.120'
    user: 'root'
    password: "s3CDfgfbFZcFEaczstX1VQrdfRFEaXTc"
    port: 3306
    describe: '120测试环境mysql配置'
# 测试环境消息推送接口配置
  mock_config_120:
    mock_url: 'http://192.168.10.10:8808/mock/message'
# 测试环境mongodb配置
  mongodb_config:
    host: '192.168.10.120'
    user: 'app'
    password: "123456"
    port: 27017
    describe: '120测试环境mongodb配置'

# mde环境mysql配置
  mysql_mde:
    host: '35.194.233.30'
    user: 'root'
    password: "BB#gCmqf3gTO5b*"
    port: 3306
    describe: 'mde测试环境mysql配置'
# mde环境消息推送接口配置
  mock_config_mde:
    mock_url: 'http://35.185.159.184:31101/mock/message'
# mde环境mongodb配置
  mongodb_mde:
    host: '35.194.233.30'
    user: 'sport_test'
    password: "BB#gCmqf3gTO5777"
    port: 27017
    describe: 'mde环境mongodb配置'


# 正式环境mysql配置
  mysql_extranet:
    host: '34.80.33.71'
    user: 'creditnetrouser'
    password: "XqtZYGfHKBBftu9"
    port: 3306
    describe: 'mde测试环境mysql配置'
# 正式环境消息推送接口配置
#  mock_config_extranet:
#    mock_url: 'http://35.185.159.184:31101/mock/message'
# 正式环境mongodb配置
  mongodb_extranet:
    host: '35.229.139.160'
    user: 'admin'
    password: "LLAt{FaKpuC)ncivEiN<Id}vQMgt(M4A"
    port: 37017
    describe: 'mde环境mongodb配置'


# 正式环境IP配置
  extranet_url:
    client_url: "https://search.betf.io"
    backend_url: "https://search.betf.best"

# mde环境IP配置
  mde_url:
    client_url: "https://mdesearch.betf.io"
    backend_url: "https://mdesearch.betf.best"

# mde环境IP配置
  120_url:
    client_url: "192.168.10.120:6210"
    backend_url: "192.168.10.120:7210"