# -*- coding: utf-8 -*-
# @Time    : 2022/05/23 19:14
# @Author  : liyang
# @FileName: config.yaml
# @Software: PyCharm

-
  environment: http://35.234.4.41:31101/mock/message
#  environment: http://192.168.10.10:8808/mock/message

-
# 测试环境mysql配置
  mysql_config:
    host: '192.168.10.120'
    user: 'root'
    password: "s3CDfgfbFZcFEaczstX1VQrdfRFEaXTc"
    port: 3306
    describe: '120测试环境mysql配置'
# 测试环境mongodb配置
  mongodb_config:
    host: '192.168.10.120'
    user: 'app'
    password: "123456"
    port: 27017
    describe: '120测试环境mongodb配置'
# mde环境mysql配置
  mysql_mde:
    host: '35.194.233.30'
    user: 'root'
    password: "BB#gCmqf3gTO5b*"
    port: 3306
    describe: 'mde测试环境mysql配置'
# mde环境mongodb配置
  mongodb_mde:
    host: '35.194.233.30'
    user: 'sport_test'
    password: "BB#gCmqf3gTO5777"
    port: 27017
    describe: 'mde环境mongodb配置'
